name: Daily data retrieval

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Date Tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build Docker Image
        run: docker build -t data-retrieval:${{ steps.date.outputs.date }} /data_retrieval

      - name: Run Docker Container
        run: docker run -d data-retrieval:${{ steps.date.outputs.date }}
